[dev]
  command = "npm start" # Command to start your dev server
  publish = "_site" # Folder with the static content for _redirect file

[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "_site"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "*"
  to = "/not-found"
  status = 404



# [[edge_functions]]
# function = "user"
# path = "/*"